version: '3.4'

services:
  bookcatalog:
    image: ${DOCKER_REGISTRY-}bookcatalog
    build:
      context: .
      dockerfile: BookCatalog/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
